### ISSUE TITLE
Source root in dev sourceset not being detected by Intellij

### ISSUE THREAD

**Issue by dinnymate** [clojurephant/clojurephant#108]
I put my user.clj in the dev sourceset because otherwise it throws an error when running the project without repl but that's normal I think. However intellij is not detecting it as a source root as you can see in the image below. So there is no autocomplete, and cursive repl is also not loading user.clj.

Intellij works with other jvm languages and also supports custom sourcesets(you can see this in the image), so the sourcesets are not hardcoded. It must be an issue with the plugin. 

![gradle-clojure](https://user-images.githubusercontent.com/12951845/47174208-42e45d80-d310-11e8-9386-b47f98d7ec99.png)

**Comment by jszakmeister** [comment]
Just to be clear, do you think this is a gradle-clojure issue or a Cursive issue?  If it's the latter, you probably want to file the ticket [here](https://github.com/cursive-ide/cursive/issues) instead.

**Comment by dinnymate** [comment]
it's definitely not a cursive issue. It should even work without cursive being installed. I only mentioned it because cursive relies on this. It is either an Intellij or a gradle-clojure issue. But many people use intellij and gradle with groovy scala or kotlin. So it looks like a plugin issue.

**Comment by jszakmeister** [comment]
Thanks.  I just wanted to check because I wasn't sure which plugin you were referring to in the context of IntelliJ. :-)  I appreciate the clarification.

**Comment by jzwolak** [comment]
I confirm that it's not a Cursive issue. Intellij defines the source directories from Gradle's sourceSets and Intellij is not picking up the sourceSets for Clojure, which should be defined somewhere by Clojurephant.

Looking over the Clojurephant documentation it seems Clojurephant does not create a source set for Clojure code but instead reuses the Java source sets. See https://clojurephant.dev/clojurephant/ and the section on "Clojure Builds" subsection "dev.clojurephant.clojure". Quote: "Applies the java plugin: Creates a main source set, whose output is packaged into a JAR via the jar task." But then later, "Applies the internal ClojureCommonPlugin which: Creates a dev source set, to be used for REPL development, which extends the test source set." From the Clojurephant documentation I believe the dev source sets would be picked up by Intellij and not other source sets (like the one that includes `src/main/clojure`).

**Comment by ajoberstar** [comment]
Should be fixed by #177
