### ISSUE TITLE
Broken `aotNamespaces = [..]`, `.add` works

### ISSUE THREAD

**Issue by holyjak** [clojurephant/clojurephant#124]
## Expected Behavior

This should make the given namespace AOT-compiled:

```
clojure {
    builds {
      main {
        aotNamespaces = ['myapp.myns']
      }
    }
}
```

## Current Behavior

Running `gradlew compileClojure` fails with

> Cannot cast object '[minbedrift.clj-jobs]' with class 'java.util.ArrayList' to class 'org.gradle.api.provider.SetProperty' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.gradle.api.provider.SetProperty(String)

**Workaround**: Replacing `... = [..]` with `aotNamespaces.add('myapp.myns')` fixes the build.

## Environment

- **gradle-clojure version:** 0.5.0-alpha.1
- **Gradle version:** Gradle 5.4.1
- **Java version:** 1.8.0_192 (Oracle Corporation 25.192-b12)
- **OS version:** Mac OS X 10.13.6 x86_64

**Comment by ajoberstar** [comment]
Long delayed, but I have a fix coming for this.

**Comment by holyjak** [comment]
❤️
It indeed is 🎄! :-)
