### ISSUE TITLE
Impossible to use data_readers.clj(c)

### ISSUE THREAD

**Issue by holyjak** [clojurephant/clojurephant#129]
## Expected Behavior

I have a `data_readers.clj ` at the top of my classpath, with the content

```clojure
{t/inst my-data-readers-impl/instant}
```

I expect to be able to use `#t/inst"..."` in my code.

## Current Behavior

The `checkClojure` phase tries to _parse_ the file and obviously fails trying to resolve the `t/inst` symbol (namely with "_No such namespace: t_"). It *should not parse* the file.
(Perhaps `Namespaces` should just filter it out?)

```
INFO Compiling data-readers
ERROR Syntax error compiling at (data_readers.clj:0:0).
Syntax error compiling at (data_readers.clj:0:0).
No such namespace: t
...
at dev.clojurephant.plugin.common.internal.ClojureExecutor.exec(ClojureExecutor.java:30)
       at dev.clojurephant.plugin.common.internal.ClojureExecutor.exec(ClojureExecutor.java:25)
       at dev.clojurephant.plugin.clojure.tasks.ClojureCheck.check(ClojureCheck.java:119)
```

## Steps to reproduce

Create `clj-jobs/src/main/clojure/data_readers.clj.ignore` with

```clojure
{whatever/sym clojure.core/str}
```

and run `gradlew test`

## Environment

- **clojurephant version:** 0.5.0-alpha.5
- **Gradle version:** 5.3
- **Java version:** 1.8.0_192 (Oracle Corporation 25.192-b12)
- **OS version:** Mac OS X 10.13.6 x86_64

**Comment by ajoberstar** [comment]
Long delay, but a fix is incoming for this.

**Comment by holyjak** [comment]
Awesome!
