### ISSUE TITLE
Clojure sources not available from java-library projects

### ISSUE THREAD

**Issue by sattvik** [clojurephant/clojurephant#134]
## Expected Behavior

I have a multi-project build where one project, sub-b, depends on another, sub-a.  If I configure sub-a to load the java-library plug-in, I expect the Clojure sources from sub-a to be available from sub-b.

## Current Behavior

It appears that when sub-a is a java-library, the class path that sub-b uses includes:

* multi-clojurephant/sub-a/build/classes/java/main
* multi-clojurephant/sub-a/build/clojure/main

Presumably, since there is no AOT compilation by default, nothing gets put into the clojure build directory.  As a result, the sub-a Clojure sources are not found.

In contrast, if the `id 'java-lbrary'` is removed from sub-a, sub-b uses a compiled JAR that includes the sources.
 
## Context

While there are workarounds, our attempt to use Clojurephant is being impacted by this and #128 .

If you can give me some pointers on where to look, I could attempt to fix it and submit a PR.

## Steps to reproduce

I have created a minimal example at: https://github.com/sattvik/multi-clojurephant 

## Environment

- **clojurephant version:** 0.5.0
- **Gradle version:** 6.2.1
- **Java version:** 11.0.6
- **OS version:** Linux 4.19.97 amd64

**Comment by ajoberstar** [comment]
I think I finally have a fix for this, by registering the source dir as a classes dir if you're not doing AOT. This will be in 0.6.0.
