### ISSUE TITLE
Output nREPL Port For IDEs To Pick Up

### ISSUE THREAD

**Issue by ska2342** [clojurephant/clojurephant#138]
## Desired Behavior

When connecting my IDE (Emacs/Cider) to an already running `clojureRepl` I don't want to enter the port manually. The IDE should pick it up automatically.

## Context

* Improves development set up.
* Should create `.nrepl-port` file in root of project, just like [leiningen](https://github.com/technomancy/leiningen/blob/master/src/leiningen/repl.clj#L226) does

**Comment by ajoberstar** [comment]
This is fixed with the use of the OOB nrepl main. Will be in 0.6.0
