### ISSUE TITLE
Allow clojurephant to depend on other classpaths

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [clojurephant/clojurephant#172]
## Desired Behavior
Clojurephant should, when `compile<Build>Clojure.classpath.from` is used, look up from those classpaths

## Context

Currently it doesn't seem feasable to depend on langs other than java. This would also be a neater solution than preImplemention.

**Comment by ajoberstar** [comment]
@TheDrawingCoder-Gamer Which version of Clojurephant are you using?

I have some improved functionality pending in 0.7.0's alphas that might help with this.

**Comment by ajoberstar** [comment]
Closing under the assumption this is resolved. If that's not true and you want to discuss further, please reopen.
