### ISSUE TITLE
`ForkOptions` is now abstract in Gradle 8.0

### ISSUE THREAD

**Issue by jarohen** [clojurephant/clojurephant#202]
## Expected Behavior

ClojureNRepl should start on Gradle 8+

## Current Behavior

It fails with the following:

```
* What went wrong:
An exception occurred applying plugin request [id: 'dev.clojurephant.clojure', version: '0.7.0']
> Failed to apply plugin class 'dev.clojurephant.plugin.common.internal.ClojureCommonPlugin'.
   > Could not create task ':clojureRepl'.
      > Could not create task of type 'ClojureNRepl'.
         > org.gradle.api.tasks.compile.ForkOptions
```

```
Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'ClojureNRepl'.
        ... 239 more
Caused by: java.lang.InstantiationError: org.gradle.api.tasks.compile.ForkOptions
        at dev.clojurephant.plugin.clojure.tasks.ClojureNRepl.<init>(ClojureNRepl.java:30)
```

It looks like the offending call is [here](https://github.com/clojurephant/clojurephant/blob/7a1ae82879fb277d7643d4501032d2444477ba7e/src/main/java/dev/clojurephant/plugin/clojure/tasks/ClojureNRepl.java#L30) - `ForkOptions` is an abstract class now.

Looking at the 8.0 release notes, there's a [section](https://docs.gradle.org/8.0/userguide/upgrading_version_7.html#plugins_tasks_and_extension_classes_are_abstract) on some classes being made abstract, if that helps.

## Steps to reproduce

1. Clone [sample-clojurephant-clj-app](https://github.com/clojurephant/sample-clojurephant-clj-app)
2. `./gradlew wrapper --gradle-version 8`
3. `./gradlew clojureRepl`

## Environment

- **Build scan URL:** N/A
- **clojurephant version:** 0.7.0
- **Gradle version:** 8.0
- **Java version:** java-17-openjdk
- **OS version:** Manjaro

**Comment by jarohen** [comment]
Cheers @ajoberstar!

**Comment by ajoberstar** [comment]
Thanks for reporting this!

**Comment by tenaf0** [comment]
I still get this issue on both 0.8.0 beta 1 and 2 with gradle 8.3 (also on 8.1, but tried updating gradle as well in the process) and Java 17. Am I perhaps using a wrong version?

**Comment by sakurawald** [comment]
The same problem in gradle 8.4
