### ISSUE TITLE
Exception on build: class clojure.lang.Var$Unbound cannot be cast to class java.util.concurrent.Future

### ISSUE THREAD

**Issue by shilder** [clojurephant/clojurephant#208]
## Expected Behavior

CI process that uses clojurephant is stable and completes successfully every time on the same codebase

## Current Behavior

Sometimes there's an exception:

```
Execution error (ClassCastException) at dev.clojurephant.prepl/eval154 (REPL:1).
class clojure.lang.Var$Unbound cannot be cast to class java.util.concurrent.Future (clojure.lang.Var$Unbound is in unnamed module of loader 'app'; java.util.concurrent.Future is in module java.base of loader 'bootstrap')
```

Followed by

```
Exception in thread "Thread-212" java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.charAt(int)" because "this.val$cs" is null
	at us.bpsm.edn.parser.Parsers$2.read(Parsers.java:124)
	at us.bpsm.edn.parser.ScannerImpl.skipWhitespace(ScannerImpl.java:255)
	at us.bpsm.edn.parser.ScannerImpl.skipWhitespaceAndComments(ScannerImpl.java:242)
	at us.bpsm.edn.parser.ScannerImpl.scanNextToken(ScannerImpl.java:68)
	at us.bpsm.edn.parser.ScannerImpl.nextToken(ScannerImpl.java:61)
	at us.bpsm.edn.parser.ParserImpl.nextValue(ParserImpl.java:36)
	at us.bpsm.edn.parser.ParserImpl.nextValue(ParserImpl.java:28)
	at dev.clojurephant.plugin.common.internal.PreplClient.inputLoop(PreplClient.java:146)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

## Context

Happens occasionally on CI environments for me 

## Steps to reproduce

Hard to reproduce - because it's a race condition related to concurrency and multiple cores. Wasn't able to reproduce locally on laptop, only on CI environment.

## Analysis

This happens due to race condition between `PreplClient` and `Prepl` classes - their initialization logic is run concurrently.

`Prepl` init logic:

`(do (ns dev.clojurephant.prepl) (def connected (promise)) @connected nil)`

`PreplClient` init logic

`(do (require 'dev.clojurephant.prepl) (deliver dev.clojurephant.prepl/connected true))`

`def` special op is not atomic in Clojure - you can have a state when var is interned but not bound yet, and we can end up with this exception.

So my fix is to add two additional checks in `PreplClient` init logic:

`(do (when-not (bound? (ns-resolve 'dev.clojurephant.prepl 'connected)) (throw (ex-info \"Not bound yet\" {}))) (require 'dev.clojurephant.prepl) (deliver dev.clojurephant.prepl/connected true))`

First check is `ns-resolve` which will throw an exception if `dev.clojurephant.prepl` is not ready or if `connected` var is not interned yet, and another `bound?` check is to handle this special edge case when var is interned but not bound to promise yet.

I've confirmed (by adding debug output in `catch` block of `PreplClient`) that both those cases are actually triggered on my CI environment - I can see following exceptions in CI build output:

* `No namespace: dev.clojurephant.prepl found` - this one is expected
* `Cannot invoke "clojure.lang.Var.isBound()" because "p1__6657_SHARP_" is null` - not sure what's going on here, some kind of race condition again ?
* `Execution error (ExceptionInfo) at user/eval147 (REPL:1). Not bound yet` - this is new `bound?` check working

**Comment by ajoberstar** [comment]
Will release this in 0.8.0-beta.5. We already had a retry loop but I hadn't seen this scenario before. Hoping the catch block tweak will cover the need.
