### ISSUE TITLE
Quarkus can't see the Clojure classes.

### ISSUE THREAD

**Issue by tkaryadis** [clojurephant/clojurephant#216]
Quarkus can't see the Clojure classes, it generates runtime error.
Maybe its simple to fix, but i don't know how to fix it, and Quarkus people said that they will not try to support Clojure for now at least. I used so far clojurephant without problems in spring-boot and in vert.x projects.

joy.Interop is a class made from Clojure code

`
Caused by: java.lang.ClassNotFoundException: joy.Interop
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
        ... 15 more
`

To see what i did, i made a simple reproducable example here : https://github.com/tkaryadis/code-with-quarkus
./gradlew quarkusDev and going to http://localhost:8080/hello will cause the error

In spring-boot i didn't had any problems for example this demo is working fine https://github.com/tkaryadis/spring-demo

Thank you

**Comment by ajoberstar** [comment]
If quarkus doesn't support it, there's a decent chance it's not going to pan out. It wouldn't be something we'd try to explicitly support in this plugin. If Quarkus is trying to compile things at runtime in dev mode, it's hard to say how integrated Clojure would need to be to with Quarkus's internals. If it leverages Gradle's tasks to rebuild on the fly, maybe it's more possible.

That said, it may be as simple as just getting the classpath wired up properly. The example in the FAQ does just enough wiring to get clojure and java compiled, but kind of assumes you're mostly just packaging things up after that. With Quarkus needing them at runtime, it might need more hints. Usually, this might require using `--debug` on Gradle to try to see if it shows the Clojure classes on the classpath of the Quarkus task. Or sometimes, placing printlns in the right spot can do the same.

**Comment by tkaryadis** [comment]
I asked the Quarkus people, and they said they are not planning to support Clojure for now at least. They do dynamic class loading for optimizations i don't know really what might cause the problem.
I sended it here also in case that is simple to fix, because i don't know about Gradle or Quakrus internals so even if its simple i doupt i will find the solution.
Spring and Quarkus are the main java frameworks so using them from Clojure would be nice. With spring so far i don't have any problems, thank you for the plugin development! For now i will just use spring-webflux.
